name: Python Linting

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with Pylint
        run: |
          pip install pylint
          pylint */*.py --rcfile .pylintrc
      - name: Comment if linting fails
        # A comment will be posted if the linting failed
        uses: thollander/actions-comment-pull-request@master
        if: failure()
        with:
          message: 'It seems that linting failed. Remember to run pylint before pushing your code 😊 '
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
